baseURL = "https://windyboy.github.io"
title = "后花园"
copyright = "© 2016-2022 糖醋小排 版权所有."
theme = "hugo-theme-tokiwa"
keywords = "Hugo, Develop, Devops, Fun"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
# googleAnalytics = "UA-78513355-1"
googleAnalytics = 'G-V1359E3SKN'
hasCJKLanguage = true
languageCode = "cn"

[markup]
[markup.highlight]
style = "monokailight"

[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ["HTML", "RSS", "JSON"]


[params]
bannerFont = "fonts/exampleFont" 
description = """
糖醋小排的后花园
"""
math = true # for introducing $KaTEX$
# env = "production" # for Google Analytics and DISQUS.
favicon = "img/favicon-32x32.png" 
fuse = true # for searchbox. "JSON" must added to output contents. See [outputs].
useChineseFonts = true 

postDateFormat = "2006-1-2"
remark42SiteID = "backyard"
remark42Url = "https://remark.windy.me"
remark42Theme = "light"
comments = true
remark42ShowComments = 10

[menu]
# Shown in the side menu.
  [[menu.main]]
    name = "文章"
    weight = 1
    identifier = "post"
    url = "/posts/"
  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 2

[[menu.main]]
name = "分类"
url = "/categories/"
weight = 2

[[menu.main]]
identifier = "about"
name = "关于"
url = "/about/"
weight = 3

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
[social]
# email = "windyboy@gmail.com"
mail = "mailto:windyboy@gmail.com"
github = "https://github.com/windyoby"
twitter = "https://twitter.com/windysylph"
weibo = "https://weibo.com/u/1645583921"
reddit = "https://www.reddit.com/user/windysylph"